internal object Constants {
    const val attentionBeforeUsageText = "########### AUTOGENERATED. Use at your own risk AS IS no warranty! #########b#1#3#"
    const val classTopPictureText = """
        ██████╗  ██╗██████╗ 
        ██╔══██╗███║╚════██╗
        ██████╔╝╚██║ █████╔╝
        ██╔══██╗ ██║ ╚═══██╗
        ██████╔╝ ██║██████╔╝
        ╚═════╝  ╚═╝╚═════╝                   
        """
    const val isInDebug: Boolean = false
}
